//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortestPathUnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShortestPathUnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A B C D E F G H
        ///A H
        ///
        ///A B 10
        ///A C 15
        ///C H 20
        ///B H 15.
        /// </summary>
        internal static string input01 {
            get {
                return ResourceManager.GetString("input01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A B C D E F G H
        ///B H
        ///
        ///A B 10
        ///A C 15
        ///C H 20
        ///B H 15.
        /// </summary>
        internal static string input02 {
            get {
                return ResourceManager.GetString("input02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 2 3 4 5
        ///1 5
        ///
        ///1 2 2
        ///2 5 5
        ///2 3 4
        ///1 4 1
        ///4 3 3
        ///3 5 1.
        /// </summary>
        internal static string input03 {
            get {
                return ResourceManager.GetString("input03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a s 2 6 7 5 3 4 t
        ///s t
        ///
        ///s 2 9
        ///s 6 14
        ///s 7 15
        ///2 3 24
        ///6 3 18
        ///6 5 30
        ///6 7 5
        ///7 5 20
        ///7 t 44
        ///5 4 11
        ///5 t 16
        ///3 5 2
        ///3 t 19
        ///4 3 6
        ///4 t 6
        ///.
        /// </summary>
        internal static string input04 {
            get {
                return ResourceManager.GetString("input04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A B H
        ///
        ///25.
        /// </summary>
        internal static string output01 {
            get {
                return ResourceManager.GetString("output01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B H
        ///
        ///15.
        /// </summary>
        internal static string output02 {
            get {
                return ResourceManager.GetString("output02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 4 3 5
        ///
        ///5.
        /// </summary>
        internal static string output03 {
            get {
                return ResourceManager.GetString("output03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a s 6 3 5 t
        ///
        ///50.
        /// </summary>
        internal static string output04 {
            get {
                return ResourceManager.GetString("output04", resourceCulture);
            }
        }
    }
}
